
## Used for a domain valid website 

# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: amazon-app-cert
#   namespace: default
# spec:
#   secretName: my-app-tls
#   issuerRef:
#     name: letsencrypt-nginx
#     kind: Issuer
#   commonName: amazon.pumej.com
#   dnsNames:
#     - amazon.pumej.com

## Used for selfsigned-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: amazon-app-cert
  namespace: default
spec:
  commonName: amazon.local
  dnsNames:
    - amazon.local
  secretName: amazon-app-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer

